tap "homebrew/core"
tap "Kreeblah/sdl-tap"

brew "sdl12-compat"
brew "sdl2"
brew "Kreeblah/sdl-tap/sdl_image"
brew "Kreeblah/sdl-tap/sdl_mixer"
brew "Kreeblah/sdl-tap/sdl_sound"
brew "cmake"
brew "make"
brew "dylibbundler"